[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "159.75.37.58"
port = "3306"
username = "m-d"
password = ""
database = ""
max_open_conn = 5
max_idle_conn = 3

[redis]
db = 0
addr = "localhost:6379"
password = ""

[log]
# Level
#   "debug", "info", "warning"
#   "error", "fatal", "panic"
level = "info"
out_dir = "logs"
format = "text"
to = "studio" # To: file, studio

[jwt]
buffer_time = 86400
expires_time = 604800
issuer = "admin"
signing_key = "4c9b2c48-df35-4e54-ba0c-d304906e9e3a"