[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "43.xxx.xxx.207"
port = "3306"
username = "username"
password = "password"
database = "dbname"
max_open_conn = 5
max_idle_conn = 3

[redis]
db = 0
addr = "43.xxx.xxx.207:6379"
password = "password"

[log]
# Level
#   "debug", "info", "warning"
#   "error", "fatal", "panic"
# To: file, studio
level = "info"
out_dir = "logs"
format = "text"
to = "studio"

[jwt]
buffer_time = 86400
expires_time = 604800
signing_key = "4c9b2c48-df35-4e54-ba0c-d304906e9e3a"
allow_num = 3
